#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

apple ()
{
    cd ~/PORTAL_PASS_TEST/video
#    if [ -f /opt/nwjs/libffmpeg.so ]; then
#        env LD_PRELOAD=/opt/nwjs/libffmpeg.so nw .
#    else
        nw .
#    fi
}

eval apple
